### ISSUE TITLE
Add a Open Source Licence

### ISSUE THREAD

**Issue by paulisawesome** [Benny-/android-accessory-protocol-bridge#2]
Could you add an open source licence like BSD or Apache 2.0 to your repo? I would like to use it but without the licence it is a bit nebulous what I can do with the code.

**Comment by Benny-** [comment]
Which one would be the most permissive?

**Comment by paulisawesome** [comment]
BSD https://opensource.org/licenses/BSD-3-Clause
Basically it allows others to use you work. They only need to cite the fact that they used your work and maintain the existing copyright info

**Comment by Benny-** [comment]
Done
